name: Generate GitHub Repo Stats

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  consumer_one_sim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Update main branch
        run: |
          git pull origin main

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Generate GitHub repo data statistics
        run: |
          python3 test_github_stats.py 12

        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DB_SOCKET_PATH: ${{ secrets.DB_SOCKET_PATH }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}

  consumer_two_sim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Update main branch
        run: |
          git pull origin main

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Generate GitHub repo data statistics
        run: |
          python3 test_github_stats.py 12 1

        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME_TWO }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_TWO }}
          DB_SOCKET_PATH: ${{ secrets.DB_SOCKET_PATH }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}

  consumer_three_sim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Update main branch
        run: |
          git pull origin main

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Generate GitHub repo data statistics
        run: |
          python3 test_github_stats.py 12 2

        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME_THREE }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_THREE }}
          DB_SOCKET_PATH: ${{ secrets.DB_SOCKET_PATH }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}

  consumer_four_sim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Update main branch
        run: |
          git pull origin main

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Generate GitHub repo data statistics
        run: |
          python3 test_github_stats.py 12 3

        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME_FOUR }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOUR }}
          DB_SOCKET_PATH: ${{ secrets.DB_SOCKET_PATH }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}

  deployment_sim:
    runs-on: ubuntu-latest

    needs:
      - consumer_one_sim
      - consumer_two_sim
      - consumer_three_sim
      - consumer_four_sim

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Create new branch
        run: |
          git fetch
          git checkout files_branch 3>/dev/null || git checkout -b files_branch
          git pull origin files_branch

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Retrieve DB data and save to .json
        run: |
          python3 db_manager.py

        env:
          DB_SOCKET_PATH: ${{ secrets.DB_SOCKET_PATH }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}

      - name: Commit to the repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Auto Update GitHub stats images' || echo
          git push origin files_branch
